# Generated by Django 4.1.5 on 2023-10-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], max_length=100, verbose_name='Status of the category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], max_length=100, verbose_name='Status of the product'),
        ),
    ]
